#!/bin/bash


#declare -a app=('ls' 'pwd' 'cat shnote.sh')

app[0]='/home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/401.bzip2/run/run_base_ref_amd64-m64-gcc43-nn.0000/bzip2_base.amd64-m64-gcc43-nn /home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/401.bzip2/run/run_base_ref_amd64-m64-gcc43-nn.0000/liberty.jpg'

app[1]='/home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/403.gcc/exe/gcc_base.amd64-m64-gcc43-nn /home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/403.gcc/run/run_base_test_amd64-m64-gcc43-nn.0000/cccp.i -o cccp.s'

#app[2]='/home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/473.astar/exe/astar_base.amd64-m64-gcc43-nn' '/home/xiaosha/start/cpu2006-1.1/benchspec/CPU2006/473.astar/data/test/input/lake.cfg'

events="instructions,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses,LLC-prefetches,LLC-prefetch-misses,cpu-cycles,page-faults"

for ((i = 0; i < ${#app[@]}; i++))
do
if [ $i -eq 0 ]; then
sudo perf stat -e $events ${app[0]} > CmdOutput.txt 2> CtOutput.txt
else
sudo perf stat -e $events ${app[$i]} >> CmdOutput.txt 2>> CtOutput.txt
fi
done
 
